spring:
  profiles:
    default: openai
  jpa:
    hibernate:
      ddl-auto: update

ollama:
  base-url: http://localhost:11434
  model: llama2
  containerized: true

openai:
  model: gpt-3.5-turbo
  api-key: demo

logging:
  level:
    dev.langchain4j: Trace

embeddings:
  knowledge: src/main/resources/knowledge/
